version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: reincornation3978
      POSTGRES_USER: myuser
      POSTGRES_DB: user-go
    ports:
      - "5432:5432"
    restart: unless-stopped
